export const INCREMENT_COUNTER = "INCREMENT_COUNTER";

export const DECREMENT_COUNTER = "DECREMENT_COUNTER";

export const INCREMENT_COUNTER_BY_AMOUNT = "INCREMENT_COUNTER_BY_AMOUNT";

export const DECREMENT_COUNTER_BY_AMOUNT = "DECREMENT_COUNTER_BY_AMOUNT";
